const $=id=>document.getElementById(id),D=$('display'),E=$('expression'),H=$('history'),SM=$('settingsModal'),SC=$('scientific'),T=$('toast');
let input='',current='0',done=false,memory=Number(localStorage.getItem('aitherCalculatorMemory')||0),angle=localStorage.getItem('aitherCalculatorAngle')||'DEG',ans=Number(localStorage.getItem('aitherCalculatorAns')||0),history=JSON.parse(localStorage.getItem('aitherCalculatorHistory')||'[]');
const settings=Object.assign({scientific:false,dark:true,haptic:true,sound:false,autoCopy:false},JSON.parse(localStorage.getItem('aitherCalculatorSettings')||'{}'));
const units={length:{meter:1,kilometer:1000,centimeter:.01,millimeter:.001,inch:.0254,foot:.3048,yard:.9144,mile:1609.344},mass:{gram:1,kilogram:1000,milligram:.001,ounce:28.349523125,pound:453.59237},speed:{'m/s':1,'km/h':.2777777778,mph:.44704,'ft/s':.3048,knot:.5144444444}};
const labels={length:{meter:'Meters',kilometer:'Kilometers',centimeter:'Centimeters',millimeter:'Millimeters',inch:'Inches',foot:'Feet',yard:'Yards',mile:'Miles'},mass:{gram:'Grams',kilogram:'Kilograms',milligram:'Milligrams',ounce:'Ounces',pound:'Pounds'},speed:{'m/s':'Meters/second','km/h':'Kilometers/hour',mph:'Miles/hour','ft/s':'Feet/second',knot:'Knots'},temperature:{c:'Celsius',f:'Fahrenheit',k:'Kelvin'}};
const save=()=>{localStorage.setItem('aitherCalculatorHistory',JSON.stringify(history));localStorage.setItem('aitherCalculatorSettings',JSON.stringify(settings));localStorage.setItem('aitherCalculatorMemory',memory);localStorage.setItem('aitherCalculatorAngle',angle);localStorage.setItem('aitherCalculatorAns',ans);dispatchEvent(new CustomEvent('aither:local-data-changed'))};
function feedback(){if(settings.haptic&&navigator.vibrate)navigator.vibrate(8);if(settings.sound)try{const C=window.AudioContext||window.webkitAudioContext,c=new C,o=c.createOscillator(),g=c.createGain();o.frequency.value=520;g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.045)}catch{}}
const round=n=>Number.parseFloat(Number(n).toPrecision(12)),fmt=n=>Number(n).toLocaleString('en-US',{maximumFractionDigits:10});
function render(){D.textContent=current;E.textContent=input;renderHistory()}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(m){T.textContent=m;T.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>T.classList.remove('show'),1800)}
function append(v){feedback();if(current==='Error'){input='';current='0'}if(done&&!/[+−×÷^)]/.test(v))input='';done=false;input+=v;current=input.match(/(?:\d*\.?\d+|π|e|Ans|[a-z]+)$/i)?.[0]||current;render()}
function num(n){append(n)}
function decimal(){feedback();if(done){input='';current='0';done=false}if(/(?:\d+\.\d*)$/.test(input))return;if(!input||/[+−×÷^(]$/.test(input))input+='0';input+='.';current=input.match(/(?:\d*\.?\d+)$/)?.[0]||'0';render()}
function clear(f=true){if(f)feedback();input='';current='0';done=false;render()}
function backspace(){feedback();if(done){clear(false);return}input=input.slice(0,-1);current=input.match(/(?:\d*\.?\d+|π|e|Ans|[a-z]+)$/i)?.[0]||'0';render()}
function evaluate(s){s=s.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('π','pi').replace(/\s/g,'');let i=0;
 const peek=()=>s[i]||'',eat=c=>s.startsWith(c,i)&&(i+=c.length,true);
 function primary(){if(eat('(')){const v=add();if(!eat(')'))throw 0;return v}if(peek()==='-'||peek()==='+'){const z=peek()==='-'?-1:1;i++;return z*primary()}if(/[0-9.]/.test(peek())){let st=i;while(/[0-9.]/.test(peek()))i++;const n=Number(s.slice(st,i));if(!Number.isFinite(n))throw 0;return n}if(s.startsWith('pi',i)){i+=2;return Math.PI}if(s.startsWith('Ans',i)){i+=3;return ans}if(peek()==='e'){i++;return Math.E}const m=s.slice(i).match(/^[a-z]+/i);if(!m)throw 0;i+=m[0].length;const name=m[0].toLowerCase();if(!eat('('))throw 0;const v=add();if(!eat(')'))throw 0;const r=angle==='DEG'?v*Math.PI/180:v;return({sin:Math.sin(r),cos:Math.cos(r),tan:Math.tan(r),sqrt:Math.sqrt(v),square:v*v,cube:v*v*v,abs:Math.abs(v),log:Math.log10(v),ln:Math.log(v),fact:fact(v)})[name]}
 function power(){let v=primary();if(eat('^'))v=v**power();return v}
 function post(){let v=power();for(;;){if(eat('%'))v/=100;else if(eat('!'))v=fact(v);else return v}}
 function mul(){let v=post();while(peek()==='*'||peek()==='/'){const op=peek();i++;const b=post();if(op==='/'&&b===0)throw 0;v=op==='*'?v*b:v/b}return v}
 function add(){let v=mul();while(peek()==='+'||peek()==='-'){const op=peek();i++;const b=mul();v=op==='+'?v+b:v-b}return v}
 const r=add();if(i!==s.length||!Number.isFinite(r))throw 0;return round(r)}
function fact(n){if(n<0||!Number.isInteger(n)||n>170)throw 0;let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function equal(){feedback();try{const r=evaluate(input),shown=input;current=String(r);ans=r;history.unshift({expression:shown,result:String(r),time:Date.now()});history=history.slice(0,100);done=true;save();if(settings.autoCopy)copy();render()}catch{current='Error';done=true;render();toast('Check the expression')}}
function sci(fn){append(fn+'(');input+=')';equal()}
function constant(n){append(n==='pi'?'π':n==='e'?'e':'Ans')}
function memoryAction(a){feedback();const n=Number(current);if(a==='MC')memory=0;else if(a==='MR'){input=String(round(memory));current=input;done=true}else if(a==='M+'&&Number.isFinite(n))memory+=n;else if(a==='M−'&&Number.isFinite(n))memory-=n;save();toast(`Memory: ${fmt(memory)}`);render()}
function sign(){feedback();if(input){input=input.startsWith('−')?input.slice(1):`−(${input})`;done=false;render()}}
function reciprocal(){append('1÷(');input+=')';equal()}
async function copy(){try{await navigator.clipboard.writeText(current);toast('Result copied')}catch{toast('Copy unavailable')}}
function renderHistory(){if(!history.length){H.className='history-empty';H.textContent='Your calculations will appear here.';return}H.className='history';H.innerHTML=history.map((x,i)=>`<div class="history-item" data-history="${i}"><div><span class="history-expression">${esc(x.expression)}</span><span class="history-time">${x.time?new Date(x.time).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'}):''}</span></div><div class="history-result">${esc(x.result)}</div></div>`).join('')}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action,v=b.dataset.value;if(a==='number')num(v);else if(a==='decimal')decimal();else if(a==='clear')clear();else if(a==='backspace')backspace();else if(a==='operator')append(v);else if(a==='equals')equal();else if(a==='percent')append('%');else if(a==='sign')sign();else if(a==='function')sci(v);else if(a==='constant')constant(v);else if(a==='memory')memoryAction(v);else if(a==='copy')copy();else if(a==='reciprocal')reciprocal();else if(a==='paren')append(v)});
H.onclick=e=>{const x=e.target.closest('[data-history]');if(!x)return;const h=history[+x.dataset.history];input=h.expression;current=h.result;done=true;render()};$('clearHistory').onclick=()=>{history=[];save();render();toast('History cleared')};$('settingsBtn').onclick=()=>SM.classList.remove('hidden');$('closeSettings').onclick=()=>SM.classList.add('hidden');SM.onclick=e=>{if(e.target===SM)SM.classList.add('hidden')};
const ST=$('scientificToggle'),DT=$('darkToggle'),HT=$('hapticToggle'),SOT=$('soundToggle'),ACT=$('autoCopyToggle');ST.checked=settings.scientific;DT.checked=settings.dark;HT.checked=settings.haptic;SOT.checked=settings.sound;ACT.checked=settings.autoCopy;SC.classList.toggle('hidden',!settings.scientific);document.body.classList.toggle('light',!settings.dark);$('angleBtn').textContent=angle;
ST.onchange=()=>{settings.scientific=ST.checked;SC.classList.toggle('hidden',!settings.scientific);save()};DT.onchange=()=>{settings.dark=DT.checked;document.body.classList.toggle('light',!settings.dark);save()};HT.onchange=()=>{settings.haptic=HT.checked;save()};SOT.onchange=()=>{settings.sound=SOT.checked;save();feedback()};ACT.onchange=()=>{settings.autoCopy=ACT.checked;save()};$('angleBtn').onclick=()=>{angle=angle==='DEG'?'RAD':'DEG';$('angleBtn').textContent=angle;save();toast(`Angle mode: ${angle}`)};$('copyResult').onclick=copy;
$('forceUpdate').onclick=async()=>{SM.classList.add('hidden');toast('Checking for updates…');try{if('serviceWorker'in navigator)await Promise.all((await navigator.serviceWorker.getRegistrations()).map(r=>r.update()))}catch{}setTimeout(()=>location.reload(),600)};
function temp(v,f,t){const c=f==='c'?v:f==='f'?(v-32)*5/9:v-273.15;return t==='c'?c:t==='f'?c*9/5+32:c+273.15}function populate(){const type=$('convertType').value,f=$('fromUnit'),t=$('toUnit'),d=labels[type];f.innerHTML=Object.entries(d).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');t.innerHTML=f.innerHTML;t.selectedIndex=Math.min(1,t.options.length-1);convert()};function convert(){const type=$('convertType').value,v=Number($('convertInput').value)||0,f=$('fromUnit').value,t=$('toUnit').value,r=type==='temperature'?temp(v,f,t):v*units[type][f]/units[type][t];$('convertResult').textContent=`${fmt(round(r))} ${labels[type][t]}`};$('converterBtn').onclick=()=>{$('converterModal').classList.remove('hidden');populate()};$('closeConverter').onclick=()=>$('converterModal').classList.add('hidden');$('converterModal').onclick=e=>{if(e.target===$('converterModal'))$('converterModal').classList.add('hidden')};$('convertType').onchange=populate;$('convertInput').oninput=convert;$('fromUnit').onchange=convert;$('toUnit').onchange=convert;$('swapUnits').onclick=()=>{const f=$('fromUnit'),t=$('toUnit'),v=f.value;f.value=t.value;t.value=v;convert()};
let installPrompt=null;addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('installApp').classList.remove('hidden')});$('installApp').onclick=async()=>{if(!installPrompt){toast('Use Safari Share → Add to Home Screen');return}installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('installApp').classList.add('hidden')};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
document.addEventListener('keydown',e=>{if(/^[0-9]$/.test(e.key))num(e.key);else if(e.key==='.')decimal();else if(e.key==='Enter'||e.key==='='){e.preventDefault();equal()}else if(['+','-','*','/','^'].includes(e.key))append(e.key==='*'?'×':e.key==='/'?'÷':e.key==='-'?'−':e.key);else if(e.key==='('||e.key===')')append(e.key);else if(e.key==='%')append('%');else if(e.key==='Escape')clear();else if(e.key==='Backspace'){e.preventDefault();backspace()}});
addEventListener('aither:cloud-restored',()=>{history=JSON.parse(localStorage.getItem('aitherCalculatorHistory')||'[]');memory=Number(localStorage.getItem('aitherCalculatorMemory')||0);ans=Number(localStorage.getItem('aitherCalculatorAns')||0);render()});render();